version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    - '15672:15672'
    - '5672:5672'
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: email_fraud_detection
    volumes:
      - .data/mongodb:/db/data
    ports:
      - '27017:27017'
